### ISSUE TITLE
Create LimeLight pipeline to detect high goal and save the pipeline to GitHub

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/infinite-recharge-2020#12]
The upload pipeline and download pipeline are at the top of the limelight screen: 
![image](https://user-images.githubusercontent.com/3326002/71785406-c09f9200-2fc4-11ea-8483-31ce6ae7f8ef.png)

Creating a pipeline:
http://docs.limelightvision.io/en/latest/vision_pipeline_tuning.html

Once you can reliably detect the high goal pipeline, download the pipeline and create a pull request to add it to master

Bonus: detect the low goal and loading station targets in the same pipeline

**Comment by elizaBarnett** [comment]
Since we are having problems with the gyro everyone's taking a day to learn the limelight
