### ISSUE TITLE
implement ADIS16470 gyro in code 

### ISSUE THREAD

**Issue by Stuart1745** [PearceRobotics/infinite-recharge-2020#22]
use the guide on[https://wiki.analog.com/first/adis16470_imu_frc/java]( https://wiki.analog.com/first/adis16470_imu_frc/java 
) to do this.

**Comment by kushagharahi** [comment]
Closing this since we already have a story open for the ADIS gyro: https://github.com/PearceRobotics/infinite-recharge-2020/issues/8
