### ISSUE TITLE
Turn leds lime green when we have the target in view, animated if not in view

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/infinite-recharge-2020#33]
This requires #13 to be complete

**Comment by nbgray** [comment]
Here's some guidance:

In lights command, you'll need to add the limelight as a member.  Make sure to add it to the constructor too.

The limelight is not currently on Master, but it will get added tonight (2/20).

In execute, call the limelight.getValidTarget, and if it's true, call limelight.getHorizontalTargetOffset, and compare it to a deadband.  If it's smaller than the deadband, call lights.allLimeGreen.  If anything isn't true, call lights.idleAnimation.

Add in a check to see if we're already in light.idleAnimation.  If so, don't call it again.
