### ISSUE TITLE
Create a Basic Dashboard with Oblog

### ISSUE THREAD

**Issue by Stuart1745** [PearceRobotics/infinite-recharge-2020#4]
Create a dashboard using the Shuffledashboard:
https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/getting-started/shuffleboard-tour.html

Add Oblog https://oblog-docs.readthedocs.io/en/latest/getting-started.html and get the webcam stream showing up:
https://oblarg.github.io/Oblog/io/github/oblarg/oblog/annotations/Log.CameraStream.html

**Comment by elizaBarnett** [comment]
Just doesn't have limelight, and we can do that when the limelight is working

**Comment by Stuart1745** [comment]
I have a limelight in my bag Ill bring it today
