### ISSUE TITLE
Create a button on shuffleboard to disable drive straight code during teleop

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/infinite-recharge-2020#46]
This is to be able to disable that code if it glitches or has a sensor failure, so we can fall back on manual driving. This should be accomplished programmatically, using oblog

**Comment by elizaBarnett** [comment]
I'm just going to add this to our curvature/teleop dropdown on shuffleboard, and have it to where you can default to differential drive's teleop drive method if everything else goes wrong

**Comment by elizaBarnett** [comment]
Basically done, I'll test it as soon as I can
