### ISSUE TITLE
Get smolboi driving

### ISSUE THREAD

**Issue by Stuart1745** [PearceRobotics/infinite-recharge-2020#5]
Basic driving working on Smolboi
Check out the drive code for deep-space-2019 here: https://github.com/PearceRobotics/deep-space-2019/tree/master/src/main/java/org/usfirst/frc1745/deepspace2019/subsystems/drive

You will need to write 3 classes at the minimum:
Gearbox.java
Drive.java
Controls.java

Use the new xbox controller for the controls.

These three classes will be integrated in the robot.java class
All of this code should be extremely similar to the 2019 code. Please refer to it.

We are using arcade drive and not tank drive.

You will need to install the  rev robotics spark max library:
    Open your robot project in VSCode.
    Click on the WPI icon in the corner to open the WPI Command Pallet.
    Select Manage Vendor Libraries.
    Select Install new library (online).
    Enter the following installation URL and press ENTER:

    https://www.revrobotics.com/content/sw/max/sdk/REVRobotics.json

**Comment by kushagharahi** [comment]
@elizaBarnett, why was this closed?

**Comment by elizaBarnett** [comment]
I don't recall closing it

**Comment by elizaBarnett** [comment]
I must have accidentally clicked close and comment instead of comment

**Comment by kushagharahi** [comment]
No worries, just wondering!
