### ISSUE TITLE
Spike: Drive: Implement cheesy drive

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/infinite-recharge-2020#50]
Let's determine if we think cheesy/differential drive would be helpful to our drivers.

> Cheesy/Curvature Drive is not arcade drive. Curvature drive has a constant curvature for a given turn stick value, so it will drive like a car. The turn joystick controls curvature rather than rate of turn. Because of this, you cannot spin in place by simply moving the turn joystick. This makes the robot way easier to control at high speeds since it won't be able to turn in place while going full speed down the field

https://old.reddit.com/r/FRC/comments/80679m/what_is_curvature_drive_cheesy_drive/
https://github.com/Team254/FRC-2016-Public/blob/master/src/com/team254/frc2016/CheesyDriveHelper.java
https://github.com/Team254/FRC-2019-Public/blob/master/src/main/java/com/team254/frc2019/subsystems/Drive.java#L278https://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.html

Depends on #8 (gyro rotation) being completed. 

Add a button on the Shuffleboard to allow operators override to regular arcade drive in case something goes wrong during a match.

After implementing get feedback if it is an improvement from a few past drivers. Let each person drive the robot for 2 minutes with arcade drive and 2 minutes with cheesy drive. Some of these people might include James, Will, Eliza etc.

**Comment by Stuart1745** [comment]
this with push to turn might be interesting.

**Comment by elizaBarnett** [comment]
should I use the differential drive class from the wpilib or should I base my code off of the links in this post?

**Comment by nbgray** [comment]
I suggest starting with the differential drive wpilib class.  If that doesn't work out we can implement our own way.

**Comment by nbgray** [comment]
Also, I have some ideas:

When turn speed is within your drive straight deadband, you should keep using the drive straight code you already have that works really well.
When drive speed is 0 (or maybe use the drive straight deadband for this too), you should use the arcade drive code that we already have, so that it turns fast.
When both turn and drive speed are not within the deadband, then use cheesy drive.

**Comment by nbgray** [comment]
Eliza, I have some math for slothDrive (maybe we need a better name).  If you want to figure it out on your own, just ignore this.

SLOTH_CURVE_CONSTANT = 1.01; //May adjust this for faster turning, making it smaller will make us turn faster
MAX_POWER = 1.0;
MIN_POWER = -1.0; 

Left power = -1.0 * max(min(speed + ((SLOTH_CURVE_CONSTANT - abs(speed)) * turn)), MAX_POWER), MIN_POWER);
Right power = max(min(speed - ((SLOTH_CURVE_CONSTANT - abs(speed)) * turn)), MAX_POWER), MIN_POWER);

**Comment by Stuart1745** [comment]
@nbgray  . . . slothDrive I love it!

**Comment by elizaBarnett** [comment]
I just tested it in the field room and it seems to be working okay, it might have just been the battery. Once a mentor gets here I will test the current code in the hallway to test it at faster speeds

**Comment by elizaBarnett** [comment]
haven't added button yet, will add it
