### ISSUE TITLE
Create buttons on shuffleboard to switch limelight pipelines

### ISSUE THREAD

**Issue by kushagharahi** [PearceRobotics/infinite-recharge-2020#65]
This is so we have a manual override in case our auto pipeline switch fails during a match.

**Comment by elizaBarnett** [comment]
Created Limelight Button branch that has the switch statement already added, the pipelines just need to be put into the switch statements.

**Comment by elizaBarnett** [comment]
https://docs.limelightvision.io/en/latest/using_multiple_pipelines.html

**Comment by elizaBarnett** [comment]
I can't use the robot right now, so I will work on this. It'll be one button, it will be green when it's for onto the high goal, and red when it is for the low goal
