### ISSUE TITLE
Turn IndexerOuttake into a command

### ISSUE THREAD

**Issue by nbgray** [PearceRobotics/infinite-recharge-2020#69]
Create an IndexerOuttakeCommand.  Turn the IndexerController class into a SubsystemBase extension.  Set a button in the Operator Inputs class (currently named IO, but I will get it renamed) to trigger the command.  Ensure that the IndexerOuttakeCommand interrupts the ShooterCommand.

**Comment by elizaBarnett** [comment]
everything for this is in master except the interruption. I'll make sure the shooter class that has the motors extends subsystem, and that the outtake command requires that subsystem. That should override the shooter command
